### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mark-monteiro** [montein56/Library#1]
Hi! Finally got around to giving this more of an in-depth review. Hope it is helpful

- [ ] The form to add a new book is not validated. It is possible to add a book with no name. Same with author, though maybe that field is not meant to be required.
- [ ] This popup appears after performing various things. Seems unnecessary and annoying
       ![image](https://user-images.githubusercontent.com/2626103/163912761-bca4f953-ad0a-4902-81bd-516fc3a6d44e.png)
- [ ] The page should not refresh every time a book is added/removed, sort order is changed, etc. The display of books should refresh without reloading the page. Instead of reloading the page, just clear the HTML for the books and then regenerate it with the updated library (using the `displayBooks()` function)
- [ ] `<ul>` is a poor choice of element for the book cards, I would probably have chosen a `<div>`. You also have items other than `<li>` nested in the `<ul>`, which will render fine, but is technically invalid HTML
- [ ] You've made a custom `<deleteicon>` element, it would be better to use a <button>
- [ ] Instead of storing "Yes" and "No" for the book read status, just store the boolean value directly. True/False is a better way to represent this
- [ ] I don't think there is any need to sort the collection before removing an item or making it as read/unread
- [ ] Click handlers for the delete/read buttons are not added to the first demo book that is added. These event handlers should be added as soon as you create the elements in the `displayBooks()` function instead of with the `DOMContentLoaded` event
- [ ] The page has unnecessary vertical scrolling, even when there are only a few books.

**Comment by montein56** [comment]
All fixed except one occasion that still benefits from page refresh. Has to do with the assigning of bookID numbers versus index number in the array.

**Comment by montein56** [comment]
This is wonderful Mark.

These are things I noticed but did not consider important. I do have solutions in mind except for the last two - and one was fixed yesterday.

Regarding the 'sort' before 'delete' or change to 'read/unread' that was because the wrong 'book' was getting deleted etc. This is because I am using indexOf() to identify which book to delete. When already sorted by title, author etc, and then deleting, the indexOf() was picking the unsorted [sorted by number] index number in the array and not the bookID number. Anyway, I think I know what to do - identify the book to delete etc, by obtaining its bookID number and then its current index number.

Thanks so much for your time. This feedback is very much appreciated.

I'm polishing off the 'edit' feature which is nearly done...  🙂

Dad
________________________________
From: Mark Monteiro ***@***.***>
Sent: April 18, 2022 11:41 PM
To: montein56/Library ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [montein56/Library] Code Review (Issue #1)


Hi! Finally got around to giving this more of an in-depth review. Hope it is helpful

  *    The form to add a new book is not validated. It is possible to add a book with no name. Same with author, though maybe that field is not meant to be required.
  *    This popup appears after performing various things. Seems unnecessary and annoying
[image]<https://user-images.githubusercontent.com/2626103/163912761-bca4f953-ad0a-4902-81bd-516fc3a6d44e.png>
  *    The page should not refresh every time a book is added/removed, sort order is changed, etc. The display of books should refresh without reloading the page. Instead of reloading the page, just clear the HTML for the books and then regenerate it with the updated library (using the displayBooks() function)
  *    <ul> is a poor choice of element for the book cards, I would probably have chosen a <div>. You also have items other than <li> nested in the <ul>, which will render fine, but is technically invalid HTML
  *    You've made a custom <deleteicon> element, it would be better to use a
  *    Instead of storing "Yes" and "No" for the book read status, just store the boolean value directly. True/False is a better way to represent this
  *    I don't think there is any need to sort the collection before removing an item or making it as read/unread
  *    Click handlers for the delete/read buttons are not added to the first demo book that is added. These event handlers should be added as soon as you create the elements in the displayBooks() function instead of with the DOMContentLoaded event
  *    The page has unnecessary vertical scrolling, even when there are only a few books.
